### PR TITLE
Add `StaticBool`

### PR DESCRIPTION
**Pull request by DilumAluthge**

### CODE REVIEW

**Comment by chriselrod** [comment]
This overlaps/conflicts with https://github.com/SciML/ArrayInterface.jl/pull/111 which adds `True` and `False`.

**Comment by Tokazama** [comment]
The approach in #111 differs in that `StaticBool` is an abstract type for `True` and `False` instead of `StaticBool{true}()` or `StaticBool{false}()`. I'm not sure if there are any performance differences.

I included it in that rather large PR b/c I felt that its utility for this package was more apparent in the context of all the other changes. Hopefully that PR will be ready to merge very soon, but if there are advantages to moving some changes here first I'd be happy to facilitate that.

**Comment by DilumAluthge** [comment]
No I think it makes more sense to do #111.

@chriselrod do you think there's any perf difference between the StaticBool in this PR versus the True/False structs in #111?

**Comment by chriselrod** [comment]
There wouldn't be any runtime performance differences.
Someone who knows more about Julia's internals would have to answer on if there's a difference in compile time.

**Comment by chriselrod** [comment]
Now that I've started updating VectorizationBase for these changes, I realize making the `B` parametric is convenient for writing `@generated` functions.
```julia
@generated function foo(::Val{B}) where {B}
    if B
       # do somethiing
    else
        # do something else
     end
end
```
Now instead, I need
```julia
asbool(::Type{True}) = true
asbool(::Type{False}) = false
@generated function foo(::B) where {B <: StaticBool}
    if asbool(B)
       # do somethiing
    else
        # do something else
     end
end
```
which is slightly less convenient.

**Comment by DilumAluthge** [comment]
Hmmm. Maybe we should change it from `True <: StaticBool` and `False <: StaticBool` to `StaticBool{true}()` and `StaticBool{false}()`

**Comment by Tokazama** [comment]
I'm assuming the actual application is more like?
```
@generated function foo(::T) where {T<:Tuple}
    for p in T.parameters
        if asbool(p)
            # do somethiing
        else
            # do something else
        end
    end
end
```

I just do `p <: True`. It seems easier than `p.parameters[1]` for a parametric type.

**Comment by chriselrod** [comment]
We could do `p === True` or `p <: True` whether `True` is an alias for `StaticBool{true}` or it is its own type.
My guess would be that the parametric types are slightly less friendly to inference though, but I don't know anything about that level of code.

The example I had in mind when making my comment was when considering whether I should convert blocks of code like this to use `True` and `False` instead of `Val`s:
```julia
@generated function vstore!(
    ptr::Ptr{T}, v::T, ::Val{A}, ::Val{S}, ::Val{NT}
) where {T <: NativeTypes, A, S, NT}
    vstore_quote(T, Int, :StaticInt, 1, 1, 0, 0, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::T, i::I, ::Val{A}, ::Val{S}, ::Val{NT}
) where {T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, 1, 1, 1, 0, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::T, ::StaticInt{N}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, 1, 1, 0, N, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::Vec{W,I}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Vec, W, 1, 1, 0, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::MM{W,X,I}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, X, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, X, 1, 0, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::I, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, sizeof(T), 1, 0, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, sizeof(T), 0, 0, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::StaticInt{N}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, sizeof(T), 0, N, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::MM{W,X,StaticInt{N}}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, X, T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, X, 0, N, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::T, i::LazyMulAdd{M,O,I}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, 1, 1, M, O, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,Vec{W,I}}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Vec, W, 1, M, O, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,MM{W,X,I}}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, X, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, X*M, M, O, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,MM{W,X,StaticInt{I}}}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, X, T <: NativeTypes, M, O, I, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, X*M, M, O + M*I, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,I}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, sizeof(T), M, O, false, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::Vec{W,I}, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Vec, W, 1, 1, 0, true, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::MM{W,X,I}, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, X, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, X, 1, 0, true, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::I, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, sizeof(T), 1, 0, true, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::StaticInt{N}, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, sizeof(T), 0, N, true, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::MM{W,X,StaticInt{N}}, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, X, T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, X, 0, N, true, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,Vec{W,I}}, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Vec, W, 1, M, O, true, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,MM{W,X,I}}, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, X, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, X*M, M, O, true, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,MM{W,X,StaticInt{I}}}, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, X, T <: NativeTypes, M, O, I, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, X*M, M, O + M*I, true, A, S, NT)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,I}, m::Mask{W}, ::Val{A}, ::Val{S}, ::Val{NT}
) where {W, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, sizeof(T), M, O, true, A, S, NT)
end
```
Here `A`, `S`, and `NT` are `Bool`s.

**Comment by Tokazama** [comment]
I know it's not the prettiest, but this should work, right?

```julia
@generated function vstore!(
    ptr::Ptr{T}, v::T, ::A, ::S, ::NT
) where {T <: NativeTypes,A,S,NT}
    vstore_quote(T, Int, :StaticInt, 1, 1, 0, 0, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::T, i::I, ::A, ::S, ::NT
) where {T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, 1, 1, 1, 0, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::T, ::StaticInt{N}, ::A, ::S, ::NT
) where {T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, 1, 1, 0, N, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::Vec{W,I}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Vec, W, 1, 1, 0, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::MM{W,X,I}, ::A, ::S, ::NT
) where {W, X, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, X, 1, 0, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::I, ::A, ::S, ::NT
) where {W, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, sizeof(T), 1, 0, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, sizeof(T), 0, 0, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::StaticInt{N}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, sizeof(T), 0, N, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::MM{W,X,StaticInt{N}}, ::A, ::S, ::NT
) where {W, X, T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, X, 0, N, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::T, i::LazyMulAdd{M,O,I}, ::A, ::S, ::NT
) where {T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, 1, 1, M, O, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,Vec{W,I}}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Vec, W, 1, M, O, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,MM{W,X,I}}, ::A, ::S, ::NT
) where {W, X, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, X*M, M, O, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,MM{W,X,StaticInt{I}}}, ::A, ::S, ::NT
) where {W, X, T <: NativeTypes, M, O, I, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, X*M, M, O + M*I, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,I}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, sizeof(T), M, O, false, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::Vec{W,I}, m::Mask{W}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Vec, W, 1, 1, 0, true, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::MM{W,X,I}, m::Mask{W}, ::A, ::S, ::NT
) where {W, X, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, X, 1, 0, true, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::I, m::Mask{W}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, sizeof(T), 1, 0, true, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::StaticInt{N}, m::Mask{W}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, sizeof(T), 0, N, true, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, ::MM{W,X,StaticInt{N}}, m::Mask{W}, ::A, ::S, ::NT
) where {W, X, T <: NativeTypes, N, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, X, 0, N, true, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,Vec{W,I}}, m::Mask{W}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Vec, W, 1, M, O, true, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,MM{W,X,I}}, m::Mask{W}, ::A, ::S, ::NT
) where {W, X, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, X*M, M, O, true, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,MM{W,X,StaticInt{I}}}, m::Mask{W}, ::A, ::S, ::NT
) where {W, X, T <: NativeTypes, M, O, I, A, S, NT}
    vstore_quote(T, Int, :StaticInt, W, X*M, M, O + M*I, true, A<:True, S<:True, NT<:True)
end
@generated function vstore!(
    ptr::Ptr{T}, v::Vec{W,T}, i::LazyMulAdd{M,O,I}, m::Mask{W}, ::A, ::S, ::NT
) where {W, T <: NativeTypes, M, O, I <: IntegerTypes, A, S, NT}
    vstore_quote(T, I, :Integer, W, sizeof(T), M, O, true, A<:True, S<:True, NT<:True)
end
```

**Pull request closed without merging**
